### ISSUE TITLE
Trouble migrating from 4.2.0 to 5.0.0

### ISSUE THREAD

**Issue by fschmaljohann** [GridProtectionAlliance/osisoftpi-grafana#157]
Hello everyone,

When migrating to 5.0.0 from 4.2.0 we receive the following error message for most panels:

`error finding key A_Req0_Data in response`

When changing the panel slightly (e.g. panel title) and saving the dashboard, the error message disappears for most of the panels. However, we have a lot of panels and dashboards, so this workaround seems to be almost impossible.
Also, we experience issues when using the Max Recorded Values feature.

Is this a known problem and is there a better workaround for this?

Thanks
Frederic

**Comment by pvmagacho-nde** [comment]
At the moment that is the only solution. I can check on a conversion script.

What is the problem with "Max Recorded Values"? I am about to launch version 5.1.0 next month.

**Comment by fschmaljohann** [comment]
With Max Recorded Values, I get "z.replace is not a function". I did not look into it, but when I remove the value from the Max Recorded Value field, I see data.

**Comment by SC-66** [comment]
I have the same issue with "ie.replace is not a function" related to max recorded values

**Comment by SC-66** [comment]
> At the moment that is the only solution. I can check on a conversion script.
> 
> What is the problem with "Max Recorded Values"? I am about to launch version 5.1.0 next month.

Will issue #159 and #160 be investigated for 5.1.0 release?

**Comment by coderReview** [comment]
Still haven't found a way that is not opening the panel and saving it again.
